### ISSUE TITLE
Issues in example 14.3.1.3 page 289

### ISSUE THREAD

**Issue by xaviweise** [hanssmail/quantQ#10]
I had to do a few adaptations of the code in order to reproduce the results of example 14.3.1.3 on VAR models. In general all had to do with overloaded functions like ts.Y, ts.zt and ts.Z. 

- For ts.Y there are two versions of the same function, the only difference being the evaluation of y[;0] or y[0;]. The problem seems to be that VAR functions like ts.varOrder call the function with the wrong index order.

- For ts.zt and ts.Z the overloaded versions have an extra parameter "flag", but functions like ts.varOrder call the curried version which return a function and therefore the function fails. 

In all these cases my solution has been to rename the overloaded functions, I don't know if there is a way to impose the use of one of the specific versions, or there should be a special namespace for the VAR utility functions. 
Best regards

**Comment by Team2of2** [comment]
The unbiased estimator of a VAR(p) process is YZ'(ZZ')^-1 as described in equation (14.22) on p. 288 where Z is a Kp+1 x 1 matrix defined as Zt = (1,y_t, ..., y_{t-p+1})'. 

The code of Zt is given in p. 293. It looks like you are using the variable Zt of the vector autogressive model with exogenous variable VARX(p,q) defined as Zt = (Y_0,...,Y_{T-1}; X_0,..., X_{T-1}; .... x_1,...,x_T)' (see eq. 14.29 on p 297) instead of Zt defined in eq. 14.22 on p.288.

I will create two name spaces: one for VAR and one for VARX such that Zt for VAR is not overrriden by Zt for VARX.

To reproduce the results on p. 291, please use the code of the book. 


.quantQ.ts.vec:{[a]
    // a -- matrix	
    i:(count raze a);
    j:1;
    v:(flip a)[0;];
    while[j<i;
        v:v,/(flip a)[j;];
        j:j+1];
    :v;
 };

.quantQ.ts.zt:{[y;t;p]
    // y -- historical data (list of floating numbers) 
    // t -- time point (positive integer)
    // p -- lags (positive integer) corresponding to the order of the VAR(p) process
    :1f,.quantQ.ts.vec[y[;(t-1)-til p]];
 };

.quantQ.ts.Z:{[y;p]
    // y -- historical data (list of floating numbers) 
    // p -- lags (positive integer) corresponding to the order of the VAR(p) process
    :flip {[y;i;p]
        .quantQ.ts.zt[y;i;p]}[y;;p] each p + til (count y[0])-p;
 };

.quantQ.ts.Y:{[y;p]
    // y -- historical data (list of floating numbers) 
    // p -- lags (positive integer) corresponding to the order of the VAR(p) process
    :y[;p+til (count y[0;])-p];
 };

.quantQ.ts.varpest:{[y;p]
    // y -- historical data (list of floating numbers) used to estimate the VAR(p) model.
    // p -- order of the VAR(p) model
    :.quantQ.ts.Y[y;p] mmu (flip .quantQ.ts.Z[y;p]) mmu
        inv[.quantQ.ts.Z[y;p] mmu flip .quantQ.ts.Z[y;p]];
 };

.quantQ.ts.covarianceResidual:{[y;p]
    // y -- historical data (list of floating numbers)
    // p -- order of the VAR(p) process
    T:(count y[0])-p;
    K:count y;
    coef:1f%((T-K*p)-1f);
    :coef*(.quantQ.ts.Y[y;p] mmu flip .quantQ.ts.Y[y;p]) -
        (.quantQ.ts.Y[y;p] mmu flip .quantQ.ts.Z[y;p]) mmu
        inv[.quantQ.ts.Z[y;p] mmu flip .quantQ.ts.Z[y;p]] mmu
        (.quantQ.ts.Z[y;p] mmu flip .quantQ.ts.Y[y;p]);
 };

.quantQ.ts.eye:{[k]
    // k -- rank of matrix
    :`float$(til k)=/:til k;
 };

.quantQ.ts.beta:{[y;p]
    // y -- historical data (list of floating numbers)
    // p -- order of the VAR(p) process
    :(1f%(count y[0])-p) * (.quantQ.ts.Y[y;p] mmu
    (.quantQ.ts.eye[(count y[0])-p] - ((flip .quantQ.ts.Z[y;p]) mmu
        inv[.quantQ.ts.Z[y;p] mmu flip .quantQ.ts.Z[y;p]] mmu
        .quantQ.ts.Z[y;p]))) mmu flip .quantQ.ts.Y[y;p];
 };

.quantQ.ts.varOrder:{[y;m]
    // y -- historical data (list of floating numbers
    // m -- maximum order of the VAR process
    T:count y[0];
    K:count y;
    i:m;
    k:v1:v2:();
    while[i>0;
        lr:T*(log .quantQ.mat.det[.quantQ.ts.beta[y;i-1]])-(log .quantQ.mat.det[.quantQ.ts.beta[y;i]]);
        k:k,(m-i);
        v1:v1,lr;
        v2:v2,.quantQ.ts.pValueChi2[lr;K*K];
        i:i-1];
    :([p:k]lr:v1;pvalue:v2);
 };



.quantQ.ts.pValueChi2:{[chi;nu]
    // chi -- instance of distribution (floating)
    // nu -- degrees of freedom of the Chi2 distribution
    u:chi%2f;
    v:nu%2f;
    p:(u-v)+1f;
    pi:3.141592654f;
    term1:exp[v-u]%(p*sqrt[2*pi]);
    term2:(u % v) xexp v;
    term3:1f-((v-1f)%((p*p)+2f*u));
    term4:(12f*(v xexp 1.5f))%((12f*v)+1);
    :term1*term2*term3*term4;
 };
